# Generated by Django 5.0.6 on 2024-08-20 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, default=None, help_text='\n            This is required to upload data to show growth graphs.\n            <a href="/media/growth_excel/samples/SAMPLE_GROWTH_FORMAT.xlsx"> Sample CSV Sheet</a>\n        ', null=True, upload_to='BRANCH_DATA')),
                ('source_type', models.CharField(choices=[('ATM', 'ATM'), ('BRANCH', 'Branch')], default='ATM', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_address', models.TextField()),
                ('source_id', models.CharField(max_length=10)),
                ('source_name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('ATM', 'ATM'), ('BRANCH', 'Branch')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('SELECT', 'Yes / NO Mark'), ('TEXT', 'Text Field')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbacks.source')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerResponses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbacks.source')),
            ],
        ),
    ]
