# Generated by Django 5.0.6 on 2024-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_rename_question_question_text_remove_question_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('ATM', 'ATM'), ('BRANCH', 'Branch')], default='ATM', max_length=50),
        ),
    ]
