# Generated by Django 5.0.6 on 2024-08-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_question_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Radio', 'Radio Buttons'), ('Scoring', 'Scoring')], default='radio', max_length=10),
        ),
    ]
