# Generated by Django 5.0.6 on 2024-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_alter_option_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('ATM', 'ATM'), ('BRANCH', 'Branch')], default='ATM', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
