# Generated by Django 5.0.6 on 2024-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_reportdownload_end_date_reportdownload_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='report_column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
