# Generated by Django 5.0.6 on 2024-08-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('task_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('jobs', models.IntegerField(blank=True, null=True)),
                ('error', models.BooleanField(default=False, verbose_name='Error Faced')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed Task')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ip_address', models.CharField(max_length=20, verbose_name='User IP')),
                ('activity', models.CharField(max_length=512)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='{"error": false, "error_message": "", "completed": true, "email_sent": false, "file_uploaded": false, "executed_query": false, "created_excel": false}', null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.tasklog')),
            ],
        ),
    ]
